name: Manage Versions

on:
  workflow_dispatch:
    inputs:
      version-number:
        description: 'source version number to use'
        required: true
        default: 'vX.Y.Z'
        type: string
      version-alias:
        description: 'verion alias to map to the source version'
        required: true
        type: choice
        options: 
        - stable
        - latest
        - latest-rc

jobs:
  add-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/

      - name: Change version
        run: npm dist-tag add "sfdx-git-delta@${{ github.event.inputs.version-number }}" "${{ github.event.inputs.version-alias }}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}