---
name: Manage versions

on:
  workflow_dispatch:
    inputs:
      version-alias:
        description: version alias to map to a version number
        required: true
        type: choice
        options:
          - stable
          - latest
          - latest-rc
      version-number:
        description: version number (semver format)
        required: true
        default: vX.Y.Z
        type: string

jobs:
  add-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Change version
        run: npm dist-tag add sfdx-git-delta@${{ github.event.inputs.version-number }} ${{ github.event.inputs.version-alias }}
        env:
          NODE_AUTH_TOKEN: ${{Â secrets.NPM_TOKEN }}
