name: Release latest-rc

on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.RELEASE_PAT }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/

      - name: Cache prep
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache --frozen-lockfile

      - name: Publish to npm
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn release
          yarn publish --access public --tag "latest-rc"
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ github.token }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Install sfdx-cli
        run: npm install -g sfdx-cli

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Install new plugin version
        run: |
          echo y | sfdx plugins:install "sfdx-git-delta@latest-rc"
          sfdx plugins

      - name: Test new plugin version
        run: sfdx sgd:source:delta --help